name: Build TWRP for Armor X12

on:
  workflow_dispatch:  # avvio manuale

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install git-core gnupg flex bison gperf build-essential             zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386             lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev             libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig

      - name: Init repo
        run: |
          mkdir twrp
          cd twrp
          repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
          repo sync --force-sync --no-clone-bundle --no-tags -j$(nproc --all)

      - name: Copy device tree
        run: |
          mkdir -p twrp/device/ulefone/armorx12
          cp -r device/ulefone/armorx12/* twrp/device/ulefone/armorx12/

      - name: Build recovery
        run: |
          cd twrp
          source build/envsetup.sh
          lunch omni_armorx12-eng
          mka recoveryimage

      - name: Upload recovery image
        uses: actions/upload-artifact@v3
        with:
          name: recovery.img
          path: twrp/out/target/product/armorx12/recovery.img
